Web/DashboardUI/Controllers/DownloadsController.cs
using DashboardUI.Models;
using MediaMaintenanceLibrary;
using MediaMaintenanceLibrary.Apis;
using SDNMediaModels.Api;
using SDNMediaModels.Api.YIFY;
using SDNMediaModels.DBContext;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DashboardUI.Controllers
{
    [Authorize]
    public class DownloadsController : Controller
    {
        MediaManagerDB db = new MediaManagerDB();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Eztv(int? id)
        {
            List<EztvResult> downloads = new List<EztvResult>();

            if (!id.HasValue)
            {
                downloads = EztvApiLibrary.GetEztvDownloads();
            }
            else
            {
                int.TryParse(id.ToString(), out int results);
                downloads = EztvApiLibrary.GetEztvDownloads(pageResults: results);
            }
            

            return View(downloads.OrderBy(show => show.imdb_id));

        }

        public ActionResult Yify(int? id)
        {
            List<YIFYMovieResult> downloads = new List<YIFYMovieResult>();

            if (!id.HasValue)
            {
                downloads = YifyApiLibrary.GetYIFYMovies();
            }

            return View(downloads);
        }

        [HttpPost]
        public ActionResult AutoEztvQueueDownload(FormCollection collection)
        {
            string displayMethod = string.Empty;



            ViewBag.DownloadMethod = "Queue Download";
            ViewBag.DownloadActionStatus = "successful";
            ViewBag.DownloadFileName = collection["downloadFileName"];

            //Set the download id of the added file to pass id to check status link in alert
            ViewBag.DownloadQueueId = null;

            List<EztvResult> results = EztvApiLibrary.GetEztvDownloads();

            return View("Eztv", results);
        }

    }
}

Web/DashboardUI/Views/Downloads/Eztv.cshtml
@model IEnumerable<SDNMediaModels.Api.EztvResult>

@{
    SDNMediaModels.DBContext.MediaManagerDB db = new SDNMediaModels.DBContext.MediaManagerDB();
    var shows = db.TelevisionShows.ToList<SDNMediaModels.Television.TelevisionShow>();

    ViewBag.Title = "Eztv Downloads ";

    if (!string.IsNullOrEmpty(ViewBag.DownloadFileName))
    {

        if (ViewBag.DownloadActionStatus == "successful")
        {
            <div class="alert alert-success" style="text-align: center;" role="alert">
                <a href="#" class="close text-sm-right align-text-top" style="text-decoration: none;" data-dismiss="alert" aria-label="close">x</a>
                Automation has @(ViewBag.DownloadActionStatus)ly processed action <b>@(ViewBag.DownloadMethod)</b>: "@(ViewBag.DownloadFileName)" - [@Html.ActionLink("Check Status", "Automation", new { Id = ViewBag.DownloadQueueId })]
            </div>
        }

        if (ViewBag.DownloadActionStatus == "unsuccessful")
        {
            <div class="alert alert-danger" style="text-align: center;" role="alert">
                <a href="#" class="close text-sm-right align-text-top" style="text-decoration: none;" data-dismiss="alert" aria-label="close">x</a>
                Automation has @(ViewBag.DownloadActionStatus)ly processed action <b>@(ViewBag.DownloadMethod)</b>: "@(ViewBag.DownloadFileName)" - Please try again.
            </div>
        }

    }
}

<h2 style="text-align: center;">Eztv Torrent Download Feed</h2>
<table class="table table-hover table-dark table-bordered" id="resultsTable">
    <tr style="background-color: #2e2d2d">
        <th>
            @Html.DisplayNameFor(model => model.title)
        </th>
        <th style="text-align: center;">
            @Html.DisplayNameFor(model => model.imdb_id)
        </th>
        <th style="text-align: center;">
            @Html.DisplayNameFor(model => model.season)
        </th>
        <th style="text-align: center;">
            @Html.DisplayNameFor(model => model.episode)
        </th>
        <th style="text-align: center;">
            @Html.DisplayNameFor(model => model.seeds)
        </th>
        <th style="text-align: center;">
            @Html.DisplayNameFor(model => model.date_released_unix)
        </th>
        <th style="text-align: center;">
            @Html.DisplayNameFor(model => model.size_bytes) (in MB)
        </th>
        <th style="text-align: center;">
            Automation Actions
        </th>
    </tr>

    @foreach (var item in Model)
    {
        int.TryParse(item.season, out int seasonNum);

        if (seasonNum != 0)
        {
            <tr>
                <td style="border-collapse: collapse; border: 1px solid gray;">
                    @Html.DisplayFor(modelItem => item.title)
                </td>
                <td style="border-collapse: collapse; border: 1px solid gray; text-align: center;">
                    <span id="@item.imdb_id">@item.imdb_id</span>
                    @*@Html.DisplayFor(modelItem => item.imdb_id)*@
                </td>
                <td style="border-collapse: collapse; border: 1px solid gray; text-align: center;">
                    @Html.DisplayFor(modelItem => item.season)
                </td>
                <td style="border-collapse: collapse; border: 1px solid gray; text-align: center;">
                    @Html.DisplayFor(modelItem => item.episode)
                </td>
                <td style="border-collapse: collapse; border: 1px solid gray; text-align: center;">
                    @Html.DisplayFor(modelItem => item.seeds)
                </td>
                <td style="border-collapse: collapse; border: 1px solid gray; text-align: center;">
                    @{
                        var displayTime = DateTimeOffset.FromUnixTimeSeconds(item.date_released_unix).DateTime.ToString("MMMM dd, yyyy HH:mm:ss");

                    }

                    @Html.DisplayFor(modelItem => displayTime)
                </td>

                @{
                    bool woo = Double.TryParse(item.size_bytes, out double size);
                }

                <td style="border-collapse: collapse; border: 1px solid gray; text-align: center;">
                    @(Math.Round(((size / 1024) / 1024), 2))
                </td>

                <td style="border-collapse: collapse; border: 1px solid gray; text-align: center;">
                    <form method="post" action="@Url.Action("AutoEztvDownloadFile","Downloads")">
                        <input type="button" class="btn-xs btn-primary" style="float: left;" value="Get" /> 
                    </form>
                    <form method="post" action="@Url.Action("AutoEztvQueueDownload", "Downloads")">
                        <input type="hidden" value="@item.torrent_url" name="downloadUrl" />
                        <input type="hidden" value="@item.filename" name="downloadFileName" />
                        <input type="hidden" value="AutoQueueEztvDownload" name="downloadMethod" />
                        <input type="submit" class="btn-xs btn-outline-info" style="float: left;" value="Queue" /> 
                    </form>
                    <form method="post" action="@Url.Action("AutoEztvTrackShow", "Downloads")">
                        <input type="hidden" value="@item.filename" name="downloadFileName" />
                        <input type="button" class="btn-xs btn-outline-success" style="float: left;" value="Track" /> 
                    </form>
                </td>
            </tr>
        }
    }
</table>

@(Html.Kendo().Tooltip()
        .For("#resultsTable")
        .Filter("span")
        .ContentTemplateId("template")
        .Position(TooltipPosition.Top)
        .Width(400)
        .Height(200)
)