Web/DashboardUI/Controllers/FeedbackController.cs
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

using SDNMediaModels.DBContext;
using SDNMediaModels.Feedback;

namespace DashboardUI.Controllers
{
    public class FeedbackController : Controller
    {
        private MediaManagerDB db = new MediaManagerDB();

        [Authorize]
        public ActionResult Index()
        {
            return View(db.UserRequests.Where(r => r.RequestCompleted == 0).ToList());
        }

        public ActionResult RequestMedia()
        {
            return View("Create");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "pk_RequestID,RequestQuery,RequestType,RequestSubtype,ExistingSeries,RequestShow,RequestSeason,RequestEpisode,RequestMovie,RequestMovieYear,RequestMovieGenre,RequestCompleted")] UserRequest request)
        {
            if (ModelState.IsValid)
            {
                db.UserRequests.Add(request);
                db.SaveChanges();
                return RedirectToAction("RequestMedia");
            }

            return View(request);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            UserRequest requestedMediaItemModel = db.UserRequests.Where(s => s.pk_RequestID == id).FirstOrDefault();

            if (requestedMediaItemModel == null)
            {
                return HttpNotFound();
            }

            return View(requestedMediaItemModel);
        }

        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "pk_RequestID,RequestQuery,RequestType,RequestSubtype,ExistingSeries,RequestShow,RequestSeason,RequestEpisode,RequestMovie,RequestMovieYear,RequestMovieGenre")] UserRequest request)
        {
            if (ModelState.IsValid)
            {
                db.Entry(request).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(request);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Tasks()
        {
            return View(db.TaskQueues);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Web/DashboardUI/Controllers/LogsController.cs
using SDNMediaModels.Logs;
using System.Collections.Generic;
using System.IO;
using System.Web.Mvc;

namespace DashboardUI.Controllers
{
    public class LogsController : Controller
    {
        // GET: Logs
        public ActionResult Index()
        {
            return View();
        }
        
    }
}

Web/DashboardUI/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using SDNMediaModels.DBContext;
using SDNMediaModels.Feedback;


namespace DashboardUI.Controllers
{
    public class ReportController : Controller
    {
        private MediaManagerDB db = new MediaManagerDB();

        [Authorize]
        public ActionResult DownloadDuration()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DownloadQueues_Read()
        {
            var dls = db.DownloadQueues.Where(d => d.DownloadDuration != null).ToList<DownloadQueue>();
            List<DownloadQueue> keep = new List<DownloadQueue>(dls);

            DateTime started;
            DateTime finished;
            DateTime.TryParse("1970-12-01 00:00:00", out started);
            DateTime.TryParse("1970-12-01 00:00:00", out finished);

            int day = 0;

            foreach (var dl in dls)
            {
                DateTime.TryParse(dl.DownloadStarted.ToString(), out started);
                DateTime.TryParse(dl.DownloadFinished.ToString(), out finished);

                int.TryParse(DateTime.Now.ToString("dd"), out day);

                if (!finished.ToString("yyyy-MM-dd").Contains(DateTime.Today.ToString("yyyy")))
                {

                    //if download is not from this year, remove it
                    keep.Remove(dl);
                    
                }

                if (!finished.ToString("yyyy-MM-dd").Contains(DateTime.Today.ToString("yyyy-MM")))
                {

                    //if download is not from this month, remove it
                    keep.Remove(dl);

                }

                if ((!finished.ToString("yyyy-MM-dd").Contains(DateTime.Today.ToString($"yyyy-MM-dd"))))
                {

                    //if download is not from today or yesterday, remove it
                    keep.Remove(dl);

                }

            }

            return Json(keep.Take(50).Reverse().Select(downloadQueue => new {
                TorrentName = downloadQueue.TorrentName,
                DownloadFinished = downloadQueue.DownloadFinished,
                DownloadStarted = downloadQueue.DownloadStarted,
                TorrentStatus = downloadQueue.TorrentStatus,
                TorrentPath = downloadQueue.TorrentPath,
                DownloadDuration = downloadQueue.DownloadDuration,
                fileSize = downloadQueue.fileSize,
            }));
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        public ActionResult StorageSpace(int? id)
        {
            if (!id.HasValue)
            {
                return View();
            }
            else
            {
                return View(db.list_MediaDrives);
            }

        }


    }
}

Web/DashboardUI/Controllers/SortController.cs
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using SDNMediaModels.DBContext;
using SDNMediaModels.Sort;

namespace DashboardUI.Controllers
{

    [Authorize]
    public class SortController : Controller
    {
        private MediaManagerDB db = new MediaManagerDB();

        public ActionResult DownloadDetails(string id)
        {
            MediaManagerDB dls = new MediaManagerDB();

            var model = dls.DownloadQueues.Where(e => e.pk_torrentID == id).First();
            return PartialView("_DownloadDetails", model);
        }

        public ActionResult GetDownloads()
        {
            MediaManagerDB dls = new MediaManagerDB();
            
            return View(dls.DownloadQueues);
        }

        public ActionResult GetContents()
        {
            return View();
        }

        public ActionResult sortItems_Read([DataSourceRequest]DataSourceRequest request)
        {
            IQueryable<sortItem> sortitems = db.sortItems;
            DataSourceResult result = sortitems.ToDataSourceResult(request, MediaManagerDBModel => new {
                pk_MediaID = MediaManagerDBModel.pk_MediaID,
                filePath = MediaManagerDBModel.filePath,
                fileName = MediaManagerDBModel.fileName,
                fileNameSanitized = MediaManagerDBModel.fileNameSanitized,
                fk_fileMediaTypeID = MediaManagerDBModel.fk_fileMediaTypeID,
                fileAdded = MediaManagerDBModel.fileAdded,
                fileModified = MediaManagerDBModel.fileModified,
                hasBeenProcessed = MediaManagerDBModel.hasBeenProcessed,
                hasBeenSanitized = MediaManagerDBModel.hasBeenSanitized
            });

            return Json(result);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult sortItems_Update([DataSourceRequest]DataSourceRequest request, sortItem MediaManagerDBModel)
        {
            if (ModelState.IsValid)
            {
                var entity = new sortItem
                {
                    pk_MediaID = MediaManagerDBModel.pk_MediaID,
                    filePath = MediaManagerDBModel.filePath,
                    fileName = MediaManagerDBModel.fileName,
                    fileNameSanitized = MediaManagerDBModel.fileNameSanitized,
                    fk_fileMediaTypeID = MediaManagerDBModel.fk_fileMediaTypeID,
                    fileAdded = MediaManagerDBModel.fileAdded,
                    fileModified = MediaManagerDBModel.fileModified,
                    hasBeenProcessed = MediaManagerDBModel.hasBeenProcessed,
                    hasBeenSanitized = MediaManagerDBModel.hasBeenSanitized
                };

                db.sortItems.Attach(entity);
                db.Entry(entity).State = EntityState.Modified;
                db.SaveChanges();
            }

            return Json(new[] { MediaManagerDBModel }.ToDataSourceResult(request, ModelState));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult sortItems_Destroy([DataSourceRequest]DataSourceRequest request, sortItem MediaManagerDBModel)
        {
            if (ModelState.IsValid)
            {
                var entity = new sortItem
                {
                    pk_MediaID = MediaManagerDBModel.pk_MediaID,
                    filePath = MediaManagerDBModel.filePath,
                    fileName = MediaManagerDBModel.fileName,
                    fileNameSanitized = MediaManagerDBModel.fileNameSanitized,
                    fk_fileMediaTypeID = MediaManagerDBModel.fk_fileMediaTypeID,
                    fileAdded = MediaManagerDBModel.fileAdded,
                    fileModified = MediaManagerDBModel.fileModified,
                    hasBeenProcessed = MediaManagerDBModel.hasBeenProcessed,
                    hasBeenSanitized = MediaManagerDBModel.hasBeenSanitized
                };

                db.sortItems.Attach(entity);
                db.sortItems.Remove(entity);
                db.SaveChanges();
            }

            return Json(new[] { MediaManagerDBModel }.ToDataSourceResult(request, ModelState));
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Web/DashboardUI/Views/Shared/_AIChat.cshtml
<div class="demo-section k-content">
    @(Html.Kendo().Chat()
                .Name("chat")                
                .Events(e =>
                {
                    e.Post("onPost");
                })
    )
</div>

<style>
    .k-card > img.k-card-image {
        height: 134px;
        display: block;
    }

    .quoteCard span {
        display: block;
        float: right;
    }
</style>

<!-- Load Promise Polyfill. Required by the DialogFlow Client API.-->
<script src="https://www.promisejs.org/polyfills/promise-6.1.0.js"></script>

<!-- Load DialogFlow Client API -->
<script src="https://cdn.rawgit.com/dialogflow/dialogflow-javascript-client/50e82e62/target/ApiAi.min.js"></script>
<script>

    $(document).ready(function () {
        var chat = $("#chat").data("kendoChat");

        window.agent = new DialogFlowAgent(chat);
    });

    function onPost(e) {
        agent.postMessage(e.text);
    }

    function onToolClick(e) {
        if (e.name === "restart") {
            e.sender.postMessage("restart");
        }
    }

    var QUOTE_CARD_TEMPLATE = kendo.template(
        '<div class="k-card k-card-type-rich">' +
            '<p><strong>Your car insurance would be:</strong></p>' +
            '<div class="k-card-body quoteCard">' +
                '<div><strong>Type:</strong>' +
                '<span>#:coverage#</span></div>' +

                '<div><strong>Car model:</strong>' +
                '<span>#:make# #:model#</span></div>' +

                '<div><strong>Car cost:</strong>' +
                '<span>#:worth#</span></div>' +

                '<div><strong>Start date:</strong>' +
                '<span>#:startDate#</span></div>' +

                '<hr/><div><strong>Total:</strong>' +
                '<span>#=kendo.toString(premium, "0.00")#</span></div>' +
            '</div>' +
        '</div>'
    );
    kendo.chat.registerTemplate("quote", QUOTE_CARD_TEMPLATE);

    var PLAN_CARD_TEMPLATE = kendo.template(
        '<div class="k-card k-card-type-rich">' +
            '<div class="k-card-body quoteCard">' +

                '# for (var i = 0; i < rows.length; i++) { #' +
                '<div><strong>#:rows[i].text#: </strong>' +
                '<span>#= kendo.toString(rows[i].value, "0.00") #</span></div>' +
                '# } #' +

                '<hr/><div><strong>Total:</strong>' +
                '<span>#= kendo.toString(premium, "0.00") #</span></div>' +

            '</div>' +
        '</div>'
    );
    kendo.chat.registerTemplate("payment_plan", PLAN_CARD_TEMPLATE);
</script>

<script>
    window.DialogFlowAgent = kendo.Class.extend({
        init: function(chat) {
            this.chat = chat;
            this.userInfo = {
                id: "botty",
                iconUrl: "https://demos.telerik.com/kendo-ui/content/chat/InsuranceBot.png",
                name: "Botty McbotFace"
            };

            this.agent = new ApiAi.ApiAiClient({ accessToken: "280344fb165a461a8ccfef7e1bb47e65" });

            this.postEvent("Welcome");

            this._timestamp;
        },

        postEvent: function(event) {
            this.agent
                .eventRequest(event)
                .then($.proxy(this.onResponse, this));
        },

        postMessage: function(text) {
            this.agent
                .textRequest(text)
                .then($.proxy(this.onResponse, this));
        },

        onResponse: function(response) {
            this._timestamp = response.timestamp;

            if (response.result && response.result.fulfillment) {
                var fulfillment = response.result.fulfillment;
                var data = fulfillment.data;

                this.renderMessages(fulfillment.messages);

                if (data && data.null) {
                    this.renderAttachments(data.null);

                    this.renderSuggestedActions(data.null.suggestedActions);
                }
            }
        },

        renderMessages: function(messages) {
            var that = this;

            $(messages).each(function(index, message) {
                switch (message.type) {
                    case 0:
                        that.chat.renderMessage({ type: "text", text: message.speech, timestamp: that._timestamp }, that.userInfo);
                        break;
                    case 2:
                        that.renderSuggestedActions(message.replies.map(function(reply) { return { title: reply, value: reply }; }));
                        break;
                    default:
                }
            });

        },

        renderAttachments: function(data) {
            var that = this;
            data.attachments = $(data.attachments).map(function(index, attachment) {
                return {
                    contentType: attachment.type || "heroCard",
                    content: attachment
                };
            }).toArray();

            this.chat.renderAttachments(data, this.userInfo);
        },

        renderSuggestedActions: function(suggestedActions) {
            this.chat.renderSuggestedActions($(suggestedActions).toArray());
        }
    });
</script>

Web/DashboardUI/Views/Shared/_FooterNavBar.cshtml
<footer>
    <p style="text-align: center;">&copy; @DateTime.Now.Year Sietsma Development Networks, Inc.  All Rights Reserved.</p>
</footer>

<script type="text/javascript">

        $(document).ready(function () {
            $("#btnShowModal").click(function () {
                $("#loginModal").modal('show');
            });

            $("#btnHideModal").click(function () {
                $("#loginModal").modal('hide');
            });
        });
</script>  

Web/DashboardUI/Views/Shared/_HeaderNavBar.cshtml
@if (Request.IsAuthenticated)
{
    <nav class="navbar navbar-expand-lg navbar-dark navbar-fixed-top table-active table-bordered" style="margin-top: -50px;">
        <a class="navbar-brand text-lg-left" href="#" style="margin-right: 50px;">Sietsma Development Media v2.1 </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor02">

            <ul class="nav navbar-nav mr-auto">

                @if (!User.IsInRole("Pending"))
                {

                    if (User.IsInRole("Admin") || User.IsInRole("Moderator"))
                    {
                        <li class="dropdown navbar-light" style="margin-right: 40px;">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Reports
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li class="nav-link" style="border-bottom: 1px solid white;">@Html.ActionLink("Overview", "Overview", "Reports")</li>
                                <li class="nav-link" style="border-bottom: 1px solid white;">@Html.ActionLink("Television", "TelevisionMaster", "Reports")</li>
                                <li class="nav-link" style="border-bottom: 1px solid white;">@Html.ActionLink("Movies", "MovieMaster", "Reports")</li>
                                <li class="nav-link" style="border-bottom: 1px solid white;">@Html.ActionLink("Download Duration", "DownloadDuration", "Report")</li>
                                <li class="nav-link" style="border-bottom: 1px solid white;">@Html.ActionLink("Storage Breakdown", "StorageBreakdown", "Report")</li>
                            </ul>
                        </li>
                    }

                    <li class="dropdown" style="margin-right: 40px;">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Media
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li class="nav-link">@Html.ActionLink("Television Shows", "ShowInfo", "Media")</li>
                            <li class="nav-link">@Html.ActionLink("Movies", "Movies", "Media")</li>
                        </ul>
                    </li>

                    if (User.IsInRole("Admin"))
                    {
                        <li class="dropdown" style="margin-right: 40px;">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Automation
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li class="nav-link">@Html.ActionLink("Sort Queue", "GetContents", "Sort")</li>
                                <li class="nav-link">@Html.ActionLink("Settings", "AutomationSettings", "Sort")</li>
                            </ul>
                        </li>
                    }

                    <!-- if user is admin, show administration dropdown-->
                    if (User.IsInRole("Admin"))
                    {
                        <li class="dropdown" style="margin-right: 40px;">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Administration
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu table-dark" role="menu" style="border: 1px solid black;">
                                <li class="nav-link">@Html.ActionLink("Dashboard", "Dashboard", "Admin")</li>
                                <li class="nav-link">@Html.ActionLink("User Accounts", "ManageUsers", "Admin")</li>
                                <li class="nav-link">@Html.ActionLink("Permissions", "Permissions", "Admin")</li>
                                <li class="nav-link">@Html.ActionLink("Storage Config", "MediaDrives", "Admin")</li>
                                <li class="nav-link">@Html.ActionLink("Download History", "GetDownloads", "Sort")</li>
                                <li class="nav-link">@Html.ActionLink("To-do List", "Tasks", "Feedback")</li>
                            </ul>
                        </li>
                    }

                    if (User.IsInRole("Admin") || User.IsInRole("Moderator"))
                    {
                        <li class="dropdown" style="margin-right: 40px;">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Media Maintenance
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li class="nav-link">@Html.ActionLink("Add Show", "CreateShow", "Media")</li>
                                <li class="nav-link">@Html.ActionLink("Add Season", "AddSeason", "Media")</li>
                                <li class="nav-link">@Html.ActionLink("Add Sort Item", "AddSortItem", "Media")</li>
                                <li class="nav-link">@Html.ActionLink("Scheduling", "AutomationTasks", "Media")</li>
                                <li class="nav-link">@Html.ActionLink("Scripts", "ScriptDashboard", "Media")</li>
                            </ul>
                        </li>

                        <li class="dropdown" style="margin-right: 40px;">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Downloads
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li class="nav-link">@Html.ActionLink("Eztv Downloads", "Eztv", "Downloads")</li>
                            </ul>
                        </li>

                        <li class="dropdown" style="margin-right: 40px;">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Logs
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li class="nav-link">@Html.ActionLink("Error Logs", "ErrorLogs", "Logs")</li>
                                <li class="nav-link"><i class="fa fa-user"></i> @Html.ActionLink("User Activity", "UserLogs", "Logs")</li>
                                <li class="nav-link">@Html.ActionLink("Info Logs", "InfoLogs", "Logs")</li>
                                <li class="nav-link">@Html.ActionLink("Storage Logs", "StorageLogs", "Logs")</li>
                            </ul>
                        </li>
                    }

                    <li class="dropdown" style="margin-right: 40px;">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Feedback
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li class="nav-link">@Html.ActionLink("Request Media", "RequestMedia", "Feedback")</li>
                            <li class="nav-link">@Html.ActionLink("View Requests", "Requests", "Feedback")</li>
                        </ul>
                    </li>

                }

                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        @User.Identity.Name
                        @if (User.IsInRole("Admin"))
                        {

                            <i class="fa fa-user" style="color: black;"></i>

                        }
                        else if (User.IsInRole("User"))
                        {

                            <i class="fa fa-user" style="color: white;"></i>

                        }
                        else if (User.IsInRole("Moderator"))
                        {

                            <i class="fa fa-user-alt" style="color: yellow;"></i>

                        }
                        else if (User.IsInRole("Pending"))
                        {

                            <i class="fa fa-question-circle" style="color: white;"></i>

                        }
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" role="menu">
                        <li class="nav-link">@Html.ActionLink("Manage Settings", "Manage", "Account")</li>
                        <li class="nav-link">@Html.ActionLink("My Dashboard", "UserDashboard", "Account")</li>
                        <li class="nav-link">@Html.ActionLink("Log Off", "LogOff", "Account")</li>
                    </ul>
                </li>
            </ul>
            @if (!User.IsInRole("Pending"))
            {
                var shows_db = new SDNMediaModels.DBContext.MediaManagerDB();

                var shows = shows_db.TelevisionShows.Where(y => y.IsEnabled).OrderBy(x => x.ShowName);


                List<SDNMediaModels.UI.AutocompleteResult> shows_models = new List<SDNMediaModels.UI.AutocompleteResult>();


                List<string> shows_auto = new List<string>();

                foreach (SDNMediaModels.Television.TelevisionShow show in shows)
                {
                    //shows_auto.Add(show.ShowName);
                    shows_models.Add(new SDNMediaModels.UI.AutocompleteResult(show.ShowName, show.ShowNumSeasons.ToString(), show.ShowNumEpisodes.ToString()));
                }


                @(Html.Kendo().AutoComplete()
                                                                                .Name("autocomplete_shows")
                                                                                .Filter("contains")
                                                                                .DataTextField("ShowName")
                                                                                .MinLength(2)
                                                                                .HtmlAttributes(new { @style = "width: 300px; margin-right: 5px;" })
                                                                                .AutoWidth(true)
                                                                                .Placeholder("Search Shows...")
                                                                                .BindTo(shows_models)
                                                                                .Height(400)
                                                                                .Template("<span class=\"k-state-default\" style=\"background-image: url(" + Url.Content("~/Content/web/Customers/") +
                                                                                          "#:data.CustomerID#.jpg" +
                                                                                          ");\" ></span>" +
                                                                                          "<span class=\"k-state-default\"><h5><i class='fas fa-tv' style='height: 30px; width: 30px;'> </i>#: data.ShowName #</h5><p>#: data.ShowNumSeasons # - Seasons / #: data.ShowNumEpisodes # - Episodes</p></span>")
                                                                                .FooterTemplate("Total <strong>#: instance.dataSource.total() #</strong> items found")
                );

            }
        </div>
    </nav>
    <br />

}

Web/DashboardUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title | Sietsma Development Network</title>
    @Scripts.Render("~/bundles/jquery")
    <link href="https://kendo.cdn.telerik.com/2018.3.1017/styles/kendo.common.min.css" rel="stylesheet" type="text/css" />
    <link href="https://kendo.cdn.telerik.com/2018.3.1017/styles/kendo.mobile.all.min.css" rel="stylesheet" type="text/css" />
    <link href="https://kendo.cdn.telerik.com/2018.3.1017/styles/kendo.black.min.css" rel="stylesheet" type="text/css" />
    <script src="https://kendo.cdn.telerik.com/2018.3.1017/js/jquery.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2018.3.1017/js/jszip.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2018.3.1017/js/kendo.all.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2018.3.1017/js/kendo.aspnetmvc.min.js"></script>
    @Styles.Render("~/Content/css")

    <script src="@Url.Content("~/Scripts/kendo.modernizr.custom.js")"></script>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-j8y0ITrvFafF4EkV1mPW0BKm6dp3c+J9Fky22Man50Ofxo2wNe5pT1oZejDH9/Dt" crossorigin="anonymous">
</head>
<body>

    <style type="text/css">

        /* entire container, keeps perspective */
        .flip-container {
        perspective: 1000px;
        }
        /* flip the pane when hovered */
        .flip-container:hover .flipper, .flip-container.hover .flipper {
        transform: rotateY(180deg);
        }

        .flip-container, .front, .back {
        width: 180px;
        height: 250px;
        }

        /* flip speed goes here */
        .flipper {
        transition: 0.6s;
        transform-style: preserve-3d;
        position: relative;
        }

        /* hide back of pane during swap */
        .front, .back {
            backface-visibility: hidden;
            position: absolute;
            top: 0;
            left: 0;
            border: 1px solid black;
        }

        /* front pane, placed above back */
        .front {
        z-index: 2;
        /* for firefox 31 */
        transform: rotateY(0deg);
        }

        /* back, initially hidden pane */
        .back {
        transform: rotateY(180deg);
        }
    </style>

    @{
        Html.RenderPartial("_HeaderNavBar");
    }
    <div class="container-fluid body-content">        
        @RenderBody()
    </div>
    <div>
        <hr />

        @{
            Html.RenderPartial("_FooterNavBar");
        }

    </div>


    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>